### ISSUE TITLE
Sudo / Sudoers.d fix is slightly different in Ubuntu 15.10

### ISSUE THREAD

**Issue by dmalouf** [cogitatio/vagrant-hostsupdater#103]
I am currently using Ubuntu 15.10 with the Mate desktop.  I am using Vagrant 1.7.4 which was installed using either Synaptic or apt-get (I cannot remember) - either way, using the distribution's version.

I am very grateful for the easy-to-use "[getting around entering a password all the time](https://github.com/cogitatio/vagrant-hostsupdater#passwordless-sudo)" fix that has been provided - specifically because this is not actually a 'bug' of vagrant-hostupdater but an issue with various operating systems use of ACL.  So thank you for stepping outside the scope of this project to help us all.

I have found that I had to change one line of the suggested /etc/sudoers.d file.

Currently there is a line:
`Cmnd_Alias VAGRANT_HOSTS_REMOVE = /usr/bin/sed -i -e /*/ d /etc/hosts`

I have found that using `/usr` in this line is causing hosts-file-removal to still require a password.  I 'fixed' this by changing to simply `/bin/sed` like this:
`Cmnd_Alias VAGRANT_HOSTS_REMOVE = /bin/sed -i -e /*/ d /etc/hosts`

I assume the `/usr` version works for most folks, so I would not suggest changing it... I'm just identifying that there is an alternative that works for me in the configuration I have (cf. first paragraph).

I'm not sure if this alternative is something I should add (i.e. to `./README.md`) - I will gladly do so but I don't really want to mess with the 'homepage' without permission (out of respect).

Again, thanks for the sudoers.d help/hint to-date!

**Comment by austinpray** [comment]
Can confirm this fixed my issues on Ubuntu 14.04 with 4.2.0-30-generic kernel

```
Cmnd_Alias VAGRANT_HOSTS_ADD = /bin/sh -c echo "*" >> /etc/hosts
Cmnd_Alias VAGRANT_HOSTS_REMOVE = /bin/sed -i -e /*/ d /etc/hosts
%sudo ALL=(root) NOPASSWD: VAGRANT_HOSTS_ADD, VAGRANT_HOSTS_REMOVE
```

**Comment by martinczerwi** [comment]
Can you try using "/usr/bin/env sed" instead of the hardcoded path? This would respect the users path settings, and be more portable I think. We could also skip the notice in the readme.

**Comment by dmalouf** [comment]
@martinczerwi - good call!  New PR created just-now (#108).  Thanks for the input on this - I didn't think to be portable (much better idea!), I had my head stuck in my own environment (booo!).
