### ISSUE TITLE
Any future roadmap to add any kind of tests?

### ISSUE THREAD

**Issue by budhrg** [cogitatio/vagrant-hostsupdater#113]
Hi,

I would like to know the repo doesn't have any kind of tests(at least unit tests).

Is it in future roadmap?

**Comment by cgsmith** [comment]
Unit tests would be great! I welcome any PRs to do this :)

I can add some eventually but if you are more capable please give it a shot.

**Comment by cgsmith** [comment]
Feel free to add unit tests - going to close this issue as it is not on the roadmap at this point.
