### ISSUE TITLE
Doesn't update using multi-profiles on one vagrant

### ISSUE THREAD

**Issue by openbayou** [cogitatio/vagrant-hostsupdater#117]
Hey,
I think I may have found a problem with hostupdater using a different profile on one Virtual PC. I have a vagrant setup using one virtual PC but I have different configurations to sync a different directory and different domain name. It works on vagrant file that I created but when I make another vagrant file to use the same Virtual PC, it doesn't update my hosts file.

Is this a known bug, do I need to create a new Virtual PC with another vagrant file, or does the plugin only work with one vagrant file and one virtual PC and not one virtual PCs and multiple vagrant files?

**Comment by cgsmith** [comment]
Can you provide a minimum `Vagrantfile` that I can test? Steps to replicate will be best as well.

**Comment by openbayou** [comment]
I use an app called Hobo that manages my vagrant file. Here's everything I have:

[vagrant.zip](https://github.com/cogitatio/vagrant-hostsupdater/files/392878/vagrant.zip)

When I start up the second vagrant called dailybayou, it sets the domain items on /etc/hosts on my mac as openbayou.dev

172.28.128.3  openbayou.dev  # VAGRANT: 294b20867f343cbbb8409ff499f82d0c (defau$
172.28.128.3  www.openbayou.dev  # VAGRANT: 294b20867f343cbbb8409ff499f82d0c (d$

**Comment by openbayou** [comment]
Figured out the problem, it sets whatever was the last generated file as the vagrant file.
