### ISSUE TITLE
Doesn't update host /etc/hosts

### ISSUE THREAD

**Issue by openbayou** [cogitatio/vagrant-hostsupdater#123]
Hello,

I'm having problems with hostupdater updating the hosts file on my Mac. I'm on OS X 10.11.6 with current versions of Vagrant and VirtualBox. The host file on my Mac is owner: root and group: wheel and I've been told it's not a great idea to change the ownership of the hosts file.

This is what's in my Sudoers file:
`Cmnd_Alias VAGRANT_HOSTS_ADD = /bin/sh -c echo "*" >> /etc/hosts
Cmnd_Alias VAGRANT_HOSTS_REMOVE = /usr/bin/env sed -i -e /*/ d /etc/hosts
%wheel ALL=(ALL) NOPASSWD: VAGRANT_HOSTS_ADD, VAGRANT_HOSTS_REMOVE`

Thanks,

**Comment by cgsmith** [comment]
@openbayou try the newest version and if it doesn't work I can reopen the issue.
