### ISSUE TITLE
No access to alias while on VPN

### ISSUE THREAD

**Issue by gmisura** [cogitatio/vagrant-hostsupdater#125]
This is not a bug, but a PSA
I installed and configured the plugin, but thought for sure there was a problem because I could not reach my alias, ping nor browser.
After discussing with my co-worker, we realized that the VPN (Cisco AnyConnect in this case) was blocking access to 192.168.x.x (laments IT). Disconnected and poof, everything works perfectly. Reconnect, boom, can't reach the private VM's IP (or the alias that the plugin setups in the hosts file).

Windows 7
Cisco AnyConnect v4.0.02052

Could be a setting that was configured (that I can't control) and not necessarily a flaw of AnyConnect.

Hopefully I can save someone else a headache.

**Comment by cgsmith** [comment]
Thanks for the heads up @gmisura
