### ISSUE TITLE
Command to automatically set up sudoers file

### ISSUE THREAD

**Issue by danepowell** [cogitatio/vagrant-hostsupdater#127]
Following up on #126, it would be nice to have a command such as `vagrant hostsupdater setup-sudo` that automatically sets up your sudoers file according to the new docs.

**Comment by byanke-pcn** [comment]
I would also appreciate this - any updates on it? It would make it easier for devs who aren't quite as shell-inclined to quickly and easily set up.

**Comment by cgsmith** [comment]
This is a great idea and I lost track of it. I will give this a try shortly and see if I can get something into a release candidate.
