### ISSUE TITLE
known_hosts cleanup

### ISSUE THREAD

**Issue by simesy** [cogitatio/vagrant-hostsupdater#129]
Is it possible if, on `vagrant up` or `vagrant destroy`, this plugin could remove the applicable IP address from ~/.ssh/known_hosts file.

**Comment by cbirajdar** [comment]
@simesy I think it's a good idea to clean up known_hosts file upon vagrant halt or destroy. I have added some functionality [here](https://github.com/cbirajdar/vagrant-hostsupdater/commit/31c68b06a88184bba72d0a9144a9ada649af8d1d). The fix only works with *nix systems as there is no definitive path (at least I'm not sure) for ssh known_hosts file on windows!
