### ISSUE TITLE
Unable to install plugin on Windows

### ISSUE THREAD

**Issue by oranges13** [cogitatio/vagrant-hostsupdater#131]
I just installed Vagrant, but I'm unable to install this plugin

The error I receive is as follows:

> Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
> Bundler, the underlying system Vagrant uses to install plugins, reported an error. The error is shown below. These errors are usually caused by misconfigured plugin installations or transient network issues. The error from Bundler is:
> 
> Unable to resolve dependency: user requested 'vagrant-hostsupdater (> 0)'

**Comment by cgsmith** [comment]
What version of Vagrant and what version of Windows are you trying?

**Comment by dennis1088** [comment]
Got the same error as described above. Below are my versions.
macOS Sierra
VirtualBox 5.1.18
Vagrant 1.9.3
ruby 2.3.1p112
gem 2.5.1
bundler 1.13.3

**Comment by dennis1088** [comment]
My issue was a spelling mistake i was trying to do `vagrant plugin install vagrant-hostupdater`instead of `vagrant plugin install vagrant-hostsupdater`

**Comment by oranges13** [comment]
Unfortunately misspelling was not my issue. You can see in the initial error message:

> Installing the **'vagrant-hostsupdater'** plugin. This can take a few minutes...

So it was spelled correctly.

**Comment by daviddahl** [comment]
I am unable to install it as well, on ubuntu 16.04, virtualbox 5.1.18, vagrant 1.9.3, ruby 2.3.1p112, gem 2.5.1, bundler 1.11.2

**Comment by rcafelipegomes** [comment]
Estou tento o mesmo problema, e ainda não encontrei solução

**Comment by maykbrito** [comment]
My issue was a spelling mistake too

**Comment by cgsmith** [comment]
I will try this on Ubuntu 16.04 with what @daviddahl has mentioned. I will need someone else to try @dennis1088 setup if possible. I do not have an Apple

**Comment by EzechukwuJI** [comment]
Anyone found a way around this yet? Mine wasn't a spelling error. 
This first line worked as expected 
`vagrant plugin install vagrant-hostsupdater` but this `vagrant plugin install vagrant-hostupdater` didn't.

**Comment by Riadlx** [comment]
Hi Am trying to install vagrant hostsupdater plugin but I get this error:
$ bash install_stack.sh fullstack
Capturing output to logs/install-20171019-184043.log
Installation started at 2017-10-19 18:40:43
Installing release 'open-release/ginkgo.1'
######################################################################## 100.0%
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/win32/registry.rb:72:in `find': unknown encoding name - CP720 (ArgumentError)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/win32/registry.rb:72:in `<module:Win32>'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/win32/registry.rb:4:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/win32/resolv.rb:7:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/resolv.rb:172:in `<class:Hosts>'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/resolv.rb:169:in `<class:Resolv>'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/resolv.rb:39:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/remote_fetcher.rb:7:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/spec_fetcher.rb:2:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:38:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/bundler.rb:454:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/bundler.rb:221:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/bundler.rb:221:in `internal_install'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/bundler.rb:106:in `install'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/commands/plugin/action/install_gem.rb:29:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/commands/plugin/command/base.rb:14:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/commands/plugin/command/install.rb:32:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/commands/plugin/command/install.rb:31:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/commands/plugin/command/install.rb:31:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/commands/plugin/command/root.rb:66:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:308:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:138:in `<main>'
Installation finished at 2017-10-19 18:40:50
no matter what I did I still get the same error. I tried all the solutions I found in the Internet but without success.
Any help please.

**Comment by xzykho** [comment]
Same problem as with @dennis1088, so glad I found this. I have been tearing my hair for that missing 's' in hosts.

**Comment by GhaziTriki** [comment]
Fixed by doing this https://stackoverflow.com/questions/26141589/gem-install-error-sass-compass/26244869#26244869

**Comment by cgsmith** [comment]
Thanks @GhaziTriki

**Comment by emfluenceindia** [comment]
> My issue was a spelling mistake i was trying to do `vagrant plugin install vagrant-hostupdater`instead of `vagrant plugin install vagrant-hostsupdater`

Whoa!! What a coincidence! :)

**Comment by OC350zz** [comment]
> My issue was a spelling mistake i was trying to do `vagrant plugin install vagrant-hostupdater`instead of `vagrant plugin install vagrant-hostsupdater`

I was doing the same .. wow
