### ISSUE TITLE
Aliases should be kept in same line as host declarations?

### ISSUE THREAD

**Issue by rogeriopradoj** [cogitatio/vagrant-hostsupdater#14]
@cogitatio, I don't now if it would really be an enhancement (I've heard from @alganet we could share cookies between hosts if they were declared together).

Anyway, the way `/etc/hosts` is defined currently:

    192.168.56.101  s4aws.localhost  # VAGRANT: 0c9076b3-e38f-4b9d-b62b-210c8fc67043 (default)
    192.168.56.101  www.s4aws.localhost  # VAGRANT: 0c9076b3-e38f-4b9d-b62b-210c8fc67043 (default)

The way I think it could be:

    192.168.56.101  s4aws.localhost  www.s4aws.localhost  # VAGRANT: 0c9076b3-e38f-4b9d-b62b-210c8fc67043 (default)

@netojoaobatista, you already help me with [this gist](https://gist.github.com/netojoaobatista/5584124#file-hosts). Could you say as if what I'm proposing here is worth or not?

Thanks guys!

**Comment by cgsmith** [comment]
I dont think this is a high priority right now.

**Comment by rogeriopradoj** [comment]
:+1:

**Comment by ElawadyNet** [comment]
On my mac  "DNS Lookup" it takes more than 5 seconds to resolve hosts file domains, Once I edit hosts file and copy all domains in one line, "DNS Lookup" returned to normal time.
