### ISSUE TITLE
permission denied changing hostname

### ISSUE THREAD

**Issue by braampje** [cogitatio/vagrant-hostsupdater#140]
When I try to give the virtual machine a hostname my vagrant crashes, saying permission denied. I had to  manually change the permissions of C:\Windows\System32\drivers\etc\hosts to writable before it worked. I did it for all group and user names since I was not sure which one I needed. Do you have an easier way of doing this? thought you should at least now this.

**Comment by Graloth** [comment]
You only need to do that for the used you are trying to run vagrant under.  
As far as I've been able to find out, this is the only solution to the issue.  


This is potentially a dublicate of https://github.com/cogitatio/vagrant-hostsupdater/issues/89

**Comment by cgsmith** [comment]
The documentation talks about using UAC here: https://github.com/cogitatio/vagrant-hostsupdater#windows-uac-prompt

This should get around the issue.
