### ISSUE TITLE
Sudoers file not working on MacOS

### ISSUE THREAD

**Issue by andypattenden** [cogitatio/vagrant-hostsupdater#145]
The snippet for the sudoers file on the README is not working on MacOS for adding hosts. I'm currently on 10.13.2

Changing the add line from:
```bash
Cmnd_Alias VAGRANT_HOSTS_ADD = /bin/sh -c 'echo "*" >> /etc/hosts'
```
to:
```bash
Cmnd_Alias VAGRANT_HOSTS_ADD = /bin/sh -c echo "*" >> /etc/hosts
```
resolves the issue.

I would raise a PR with the fix but I'm not able to verify that removing the single-quotes doesn't break other OSs

**Comment by danepowell** [comment]
Thanks for finding this, see #146
