### ISSUE TITLE
Add method gets the instance public IP when provider is AWS

### ISSUE THREAD

**Issue by kentr** [cogitatio/vagrant-hostsupdater#151]
What's keeping #74 from getting into the stable branch or a release?

Thanks.

**Comment by cgsmith** [comment]
Hi @kentr just been a little busy (👶 🍼 )

I'll work on this today during my lunch break.

**Comment by cgsmith** [comment]
@kentr would you mind testing the [release](https://github.com/cogitatio/vagrant-hostsupdater/releases/tag/1.1.0) for me before I send it to RubyGems?

**Comment by cgsmith** [comment]
Part of version 1.1.0

**Comment by kentr** [comment]
Great, thx!

I’ve been meaning to reply that I couldn’t test it until next week or so.
