### ISSUE TITLE
Syntax error in 1.10 pre release

### ISSUE THREAD

**Issue by tjaartvdwalt** [cogitatio/vagrant-hostsupdater#153]
Hi, 

I tried the `1.1.0 pre-release`, but I run into some problems

I am running `ruby 2.5.0` and `vagrant 2.0.3` on Arch Linux.

Here is what I did:

`wget https://github.com/cogitatio/vagrant-hostsupdater/releases/download/1.1.0/vagrant-hostsupdater-1.1.0.gem`
`vagrant plugin install vagrant-hostsupdater-1.1.0.gem`
`vagrant up`

I get the following output:

```
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

/home/tjaart/.vagrant.d/gems/2.5.0/gems/vagrant-hostsupdater-1.1.0/lib/vagrant-hostsupdater/HostsUpdater.rb:235: syntax error, unexpected end-of-input, expecting keyword_end
```

**Comment by cgsmith** [comment]
@tjaartvdwalt thanks for testing this. I will check it out and release an patch shortly. Would you be available to test it locally again for me?

**Comment by cgsmith** [comment]
I updated the [release](https://github.com/cogitatio/vagrant-hostsupdater/releases/tag/1.1.0) with a fix. Thank you again for testing and reporting! I'm going to close this issue, if anything else pops up just open a new issue.
