### ISSUE TITLE
Plugin install failing with dependency error

### ISSUE THREAD

**Issue by gobnat** [cogitatio/vagrant-hostsupdater#164]
On both Vagrant 2.0.4 and 2.1.1 the following error occurs when trying to install this plugin. 
OS: Ubuntu 16.04

Other pugins appear to be installing correctly.

```ruby
Installing the 'vagrant-hostupdater' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-hostupdater (> 0)'
```

**Comment by sryanb** [comment]
Currently experiencing the same issue on OSX 10.13.5, with vagrant 2.1.1. Currently troubleshooting, will report back here with any findings.

**Comment by sryanb** [comment]
Ok i was able to get past this. I ended up running `vagrant plugin update vagrant-hostupdater` instead of `vagrant plugin install ...` and it updated successfully and unblocked me.

**Comment by gobnat** [comment]
This solution does not appear to fix the issue for me. The problem persists with the same error message.

**Comment by tsyrya** [comment]
Same for me. Has anybody fixed this problem?

**Comment by kennyr87** [comment]
Had this problem with Vagrant 2.1 on openSUSE Tumbleweed. The fix was to uninstall distro's Vagrant rpm and download and install for latest rpm from Vagrant.org.

Steps to Fix:

(1) uninstall vagrant
(2) remove ~/.vagrant.d (from user and root)
(3) download and install vagrant from Vagrant.org

**Comment by karlwilbur** [comment]
I'm still seeing this in 2019 on Ubuntu 18.04.2 (bionic):
```
-> % vagrant plugin install vagrant-hostupdater
Installing the 'vagrant-hostupdater' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

Unable to resolve dependency: user requested 'vagrant-hostupdater (> 0)'
```

I was using `vagrant` from Ubuntu's 18.04 repos. I ran `apt purge vagrant` to remove the installed `vagrant` (`Removing vagrant (1:2.0.3) ...`), then download and installed the latest `vagrant` from HashiCorp (`Setting up vagrant (1:2.2.5) ...`). After installing the latest version, I deleted `~/.vagrant.d` (`rm -rf ~/.vagrant.d`) and then ran `vagrant plugin install vagrant-hostupdater` (above).

**Comment by cgsmith** [comment]
@karlwilbur `vagrant plugin install vagrant-hostsupdater`

**Comment by karlwilbur** [comment]
@cgsmith Sheesh. Thanks. I *should* have seen that.
