### ISSUE TITLE
vagrant-hostupdater will use wrong IP address when using HyperV provider

### ISSUE THREAD

**Issue by ddcruver** [cogitatio/vagrant-hostsupdater#166]
When initializing a VM it seems to use the wrong IP.

> vagrant up
Bringing machine 'maven' up with 'hyperv' provider...
==> maven: Verifying Hyper-V is enabled...
==> maven: Verifying Hyper-V is accessible...
==> maven: Importing a Hyper-V instance
    maven: Creating and registering the VM...
    maven: Successfully imported VM
    maven: Please choose a switch to attach to your Hyper-V instance.
    maven: If none of these are appropriate, please open the Hyper-V manager
    maven: to create a new virtual switch.
    maven:
    maven: 1) COMPANY Network
    maven: 2) Internal Network
    maven: 3) Default Switch
    maven:
    maven: What switch would you like to use? 3
    maven: Configuring the VM...
    maven: Setting VM Integration Services
==> maven: guest_service_interface is enabled
==> maven: Starting the machine...
**==> maven: Waiting for the machine to report its IP address...
    maven: Timeout: 120 seconds
    maven: IP: 172.22.180.238**
==> maven: Waiting for machine to boot. This may take a few minutes...
    maven: SSH address: 172.22.180.238:22
    maven: SSH username: vagrant
    maven: SSH auth method: private key
==> maven: Machine booted and ready!
==> maven: [vagrant-hostsupdater] Checking for host entries
==> maven: [vagrant-hostsupdater] Writing the following entries to (C:/WINDOWS/system32/drivers/etc/hosts)
**==> maven: [vagrant-hostsupdater]   192.168.34.17  maven-vagrant-01  # VAGRANT: 34882877379cb29e9830f50f26a37597 (maven) / 81e31653-3928-43f1-9453-f5f0449c58bd**
==> maven: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.

**Comment by cgsmith** [comment]
I will need to see your vagrant file to assist.

**Comment by ddcruver** [comment]
I believe my problem is because HyperV does not support non-public networks, i.e. I could only get External HyperV switches to work. Internal and the Default Switch did not work at all.
