### ISSUE TITLE
Flush DNS cache after changes

### ISSUE THREAD

**Issue by markjaquith** [cogitatio/vagrant-hostsupdater#18]
After changing the hosts file, an effort should be made to flush the system DNS cache to make sure no old entries are lingering:

On OS X: `dscacheutil -flushcache; sudo killall -HUP mDNSResponder`

http://support.apple.com/kb/ht5343

**Comment by QWp6t** [comment]
:-1:

This isn't needed for any OS other than OS X, and even then, the command to do it is inconsistent across versions.

**Comment by cgsmith** [comment]
Not going to implement this in the plugin at this time. It might be a good idea to put this into the documentation if the issue pops up on this project.
