### ISSUE TITLE
remove_on_suspend should default to true

### ISSUE THREAD

**Issue by markjaquith** [cogitatio/vagrant-hostsupdater#19]
Regarding #4, I think having `remove_on_suspend` default to `false` is very odd.

Why would you want your hosts entries to persist if your VM is not available? They're not of any use. And if it's a real domain you're resolving, it can actually lead to confusion. The entries relate to the VM. If the VM isn't running, the entries shouldn't be there.

**Comment by Johnstonian** [comment]
+1

**Comment by cgsmith** [comment]
Fixed in [1.0.0](../releases/tag/1.0.0)
