### ISSUE TITLE
Hosts file change only happens if provisioning is successful

### ISSUE THREAD

**Issue by jhogendorn** [cogitatio/vagrant-hostsupdater#31]
#### Bug Description

Running `vagrant up` with `ansible` provisioning fails, due to the hosts file not being altered yet. Running `vagrant up --provision-with=shell` shows the hosts file being updated _after_ the provisioning call.

#### Expected behaviour 

Hostsupdater should execute its hooks prior to provisioning executing.

**Comment by cgsmith** [comment]
Hosts are not being updated before provisioning in [1.0.0](../releases/tag/1.0.0)
