### ISSUE TITLE
failed to remove hosts on vagrant 1.4.0

### ISSUE THREAD

**Issue by layerssss** [cogitatio/vagrant-hostsupdater#34]
Hi.

After I updated vagrant from 1.3.5 to 1.4.0 (I also uninstalled and re-installed `vagant-hostupdater`). The plugin failed to remove the `/etc/hosts` entries. Would you kindly please see what's broken?

here are [some debug logs](https://gist.github.com/layerssss/509b290c43dfca453693). let me know if you need other info :)

**Comment by cgsmith** [comment]
Unfortunately this issue is too old to address.  If you have a similar issue feel free to create a new issue.
