### ISSUE TITLE
Line break not inserted before first host — leads to broken lines

### ISSUE THREAD

**Issue by markjaquith** [cogitatio/vagrant-hostsupdater#37]
MAMP Pro seems to insert its rules at the end of `/etc/hosts` without a trailing line break. vagrant-hostsupdater then adds its rules after without a prepended line break. Thus, two rules get put on one line, and the vagrant-hostsupdater line does not work. I have to manually go in and fix it from time to time.

I would suggest that vagrant-hostsupdater always include a prepended line break.

**Comment by cgsmith** [comment]
Fixed in [1.0.0](../releases/tag/1.0.0)
