### ISSUE TITLE
Yellow text on white background

### ISSUE THREAD

**Issue by wizonesolutions** [cogitatio/vagrant-hostsupdater#39]
Steps to reproduce:

1. Run a command like `vagrant destroy` when you haven't created a VM.

Expected result: Black on white text.

Actual result: A message in yellow text that I have to highlight to read. It says: `==> default: No machine id, nothing removed from /etc/hosts`

There are others, and this issue is meant to refer to the yellow text in general.

**Comment by cgsmith** [comment]
Addressed in an upcoming release.
