### ISSUE TITLE
UAC issues on Windows

### ISSUE THREAD

**Issue by evertiro** [cogitatio/vagrant-hostsupdater#40]
On Windows, hostsupdater fails unless vagrant is run as an administrator. Unfortunately, this is really not the smart way to run vagrant. I know you can elevate privileges through WIN32OLE, but I'm not familiar enough with ruby to actually patch it myself. Thoughts?

**Comment by jeremiahsmall** [comment]
@itsananderson +1 for removing powershell dependency and PR'ing this.

**Comment by itsananderson** [comment]
I got busy with other things and lost track of this. I think removing the PS dependency should be doable, I just need to find the time to rewrite it. I'll see if I can set aside some time over the next weekend or two. Feel free to ping me if I forget again :)

**Comment by bretmogilefsky** [comment]
@itsananderson Can you give a pointer to that commit please? Not seeing it in the commit log for this repository.

**Comment by itsananderson** [comment]
Oh, I was wrong. I saw this: https://github.com/willenglishiv/vagrant-hostsupdater/commit/d5b031ca024b3fb4ebb087dfad357ba8b23c6f4a and incorrectly thought it was in the original repo.

I'll see if I can use that commit as a reference for doing UAC elevation in CMD, so we can get this fix into a PR.

**Comment by bretmogilefsky** [comment]
@itsananderson That'd be great!

**Comment by polarathene** [comment]
Just ran into this issue, since the last commit to the plugin was 2013 has development on this repo likely stopped for good? Which repo were you going to send the PR to?

**Comment by jeremiahsmall** [comment]
Hmm, @cogitatio has been totally silent on GitHub for the previous year. Maybe he wouldn't mind if someone took over maintenance?

**Comment by cgsmith** [comment]
Hey @jeremiahsmall I will be maintaining the project for @cogitatio - I'll be submitting updates shortly.

**Comment by jeremiahsmall** [comment]
Okay. Good to see the project lives.

**Comment by cgsmith** [comment]
:+1:

**Comment by cgsmith** [comment]
@itsananderson if youd like to submit a pull request that's be great. Otherwise I'll take a crack at it in a couple weeks.

**Comment by e7d** [comment]
I definetly support @itsananderson solution. Do the PR! :+1: 

 I'm currently using the 1.0.1 version from @cgsmith correcting this first start crash. Addressing this issue would make it perfect for Windows users, I guess.

**Comment by QWp6t** [comment]
@cgsmith @itsananderson 

This should hopefully be a good starting point...

```diff
         if !File.writable_real?(@@hosts_path)
           sudo(%Q(sh -c 'echo "#{content}" >> #@@hosts_path'))
+        elsif Vagrant::Util::Platform.windows?
+          require 'tmpdir'
+          uuid = @machine.id || @machine.config.hostsupdater.id
+          hashedId = Digest::MD5.hexdigest(uuid)
+          tmpPath = File.join(Dir.tmpdir, 'hosts-' + uuid + '.cmd')
+          File.open(tmpPath, "w") do |tmpFile|
+            entries.each { |line| tmpFile.puts(%Q(@echo #{line} >> #@@hosts_path)) }
+          end
+          sudo(tmpPath)
+          File.delete(tmpPath)
         else
           content = "\n" + content
           hostsFile = File.open(@@hosts_path, "a")
```

```diff
       def sudo(command)
         return if !command
+        if Vagrant::Util::Platform.windows?
+          require 'win32ole'
+          args = command.split(" ")
+          command = args.shift
+          sh = WIN32OLE.new('Shell.Application')
+          sh.ShellExecute(command, args.join(" "), '', 'runas', 0)
+          return
+        end
         `sudo #{command}`
       end
```

**Comment by QWp6t** [comment]
So far that code above has been working for me. Has no 3rd party dependencies. Works with multiple entries. I think that's probably the way to go. But feel free to test it on your own.

If we could get `sh.ShellExecute` to properly send line-breaks to `sh.exe`, then we could remove the temp file workaround. But so far in my testing, it just puts everything on one line.

**Comment by oniric85** [comment]
Is there any more work to do for this one? I'm willing to help as this would be a really useful addition!

**Comment by cgsmith** [comment]
Hi @oniric85 if you are willing you could pull down the code and test it out on your machine! That would be really useful! Feel free to document what it takes you to get the code running on the wiki or by writing some Markdown - thanks for offering to help!

**Comment by QWp6t** [comment]
I submitted a PR to fix this almost a year ago. I've since moved on to `vagrant-hostmanager`, though.

**Comment by cgsmith** [comment]
Thanks @QWp6t I'd like to have it tested on a Windows machine (I dont have one) and will gladly merge it in if some others can verify it is working.
