### ISSUE TITLE
Set custom ip

### ISSUE THREAD

**Issue by smgladkovskiy** [cogitatio/vagrant-hostsupdater#51]
There would be nice to have a chance to configure ip address that is used in hosts file when host entries are added. The default would be :private_network and if it necessary, user can set

```
config.hostsupdater.ip = "127.0.0.1"
```

and override defaults.

What do you think about it?

**Comment by stefanofm** [comment]
+1

**Comment by cgsmith** [comment]
Done as of 1.1.0
