### ISSUE TITLE
Adding support for docker provider.

### ISSUE THREAD

**Issue by mtbvang** [cogitatio/vagrant-hostsupdater#52]
Hi,

Are there plans to add docker provider support or is this available already and I have missed it? I tested and got the following configuration working so that the container could be accessed from my local host with the alias on the default port:

   config.vm.network "forwarded_port", guest: 8080, host: 80
   config.vm.network "private_network", ip: "127.0.0.1"
   config.hostsupdater.aliases = ["blah"]

The current version of docker updates the container IP on commands like reload and up so static IP is does not work. I was thinking that having the plugin update the host file with the new docker IP. The work around above which limits me to having only one alias to the default web port. Is there interest in adding this functionality?

Vang

**Comment by cgsmith** [comment]
@mtbvang this is merged and added as of version 1.1.0
