### ISSUE TITLE
configuration with yaml

### ISSUE THREAD

**Issue by carlituxman** [cogitatio/vagrant-hostsupdater#53]
i'm using the laravel/homestead, Homestead.yaml config has sites like "homestead.app" and in vagranfile   

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  Homestead.configure(config, YAML::load(File.read(path + '/Homestead.yaml')))
end

after up at /etc/hosts only appear "homestead" without extension

**Comment by sorinstanila** [comment]
fixed in laravel/homestead@27eec636e9d
You should only define the "name" variable in Homestead.yaml

**Comment by cgsmith** [comment]
:+1: @sorinstanila
