### ISSUE TITLE
Installation break up - Nokogiri issue

### ISSUE THREAD

**Issue by heyalbert** [cogitatio/vagrant-hostsupdater#57]
vagrant plugin install vagrant-hostsupdater
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

**Comment by timalbert** [comment]
I have this same problem.

**Comment by Johnstonian** [comment]
same problem for me as well :(

**Comment by hackeron** [comment]
Same problem here :( - weird thing running:

```
gem install nokogiri -v '1.6.6.2'
```

Succeeds without any issues - but fails when installing from bundler :/

**Comment by Johnstonian** [comment]
I experienced the same. Could it be a permissions issue?

**Comment by Johnstonian** [comment]
what version of Vagrant are ya'll using? This extremely long issue thread seems to point at upgrading to Vagrant 1.7.2. https://github.com/mitchellh/vagrant/issues/3769

I will give that a try to see that solves this dependency issue.

**Comment by Johnstonian** [comment]
Ok, upgrading to the latest version of Vagrant fixed this issue for me:

```shell
$ vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.2
 
You're running an up-to-date version of Vagrant!
```
and then:
```shell
$ vagrant plugin install vagrant-hostsupdater
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostsupdater (0.0.11)'!
```

show me the plugins!
```shell
$ vagrant plugin list
vagrant-hostsupdater (0.0.11)
vagrant-share (1.1.3, system)
```

**Comment by hackeron** [comment]
For me the issue was a dodgy 3g connection that was killing the download of nokogiri - didn't realise that bundler is so fragile and does not verify the downloaded file or try to resume if download times out or is killed!

**Comment by Advocation** [comment]
Updating Vagrant solved it for me, thanks @Johnstonian !

**Comment by carlsonorozco** [comment]
Thank you @Johnstonian, update my vagrant to latest version also fixed it.

**Comment by cgsmith** [comment]
@carlsonorozco, @heyalbert I am closing this issue as it seems it is working.  If not let me know and I can dig into what's happening.
