### ISSUE TITLE
Hostsupdater doesn't delete old changes in linux

### ISSUE THREAD

**Issue by onnimonni** [cogitatio/vagrant-hostsupdater#67]
We're using this plugin in our wordpress template. It works fine in OS X, but not in Linux. Instead of removing old entries it only adds new ones. You can see the output here:
https://github.com/Seravo/wordpress/issues/12

**Comment by cgsmith** [comment]
This will be addressed in an upcoming release.

**Comment by cgsmith** [comment]
Fixed in [1.0.0](../releases/tag/1.0.0)
