### ISSUE TITLE
allow opting out

### ISSUE THREAD

**Issue by tkellen** [cogitatio/vagrant-hostsupdater#69]
It would be nice for highly technical users to be able to opt out of using this, and for hostsupdater to provide a message stating what configuration must be added if a user opts out.

Would you accept a PR for this behavior, or consider implementing it yourself?

/cc @tbranyen @jugglinmike

**Comment by cgsmith** [comment]
I believe #62 may address this.  If so you can test it locally or submit a PR.

**Comment by tkellen** [comment]
Hey @cgsmith! This doesn't quite do the trick. Also, this project seems abandoned so I'm not holding out hope it will be merged. Hey, @cogitatio would you be willing to transfer ownership of this repo to me? I'd be happy to maintain it since you clearly don't have the time.

**Comment by cgsmith** [comment]
Hi @tkellen, @cogitatio added me as a contributor for maintaining the repository.  I'd be happy to pull in any PR that you attach for the behavior.  Let me know your thoughts.

**Comment by tkellen** [comment]
That's great news @cgsmith! I'll see what I can come up with soon.

**Comment by cgsmith** [comment]
Perfect :+1: 

I would gladly implement a solution as well if the specs of what you'd like are defined well.  This next release will focus on fixing the bugs.

**Comment by cgsmith** [comment]
Releasing in 1.0.2

**Comment by tkellen** [comment]
cc @tafsiri, it's here!

**Comment by tkellen** [comment]
thanks @cgsmith !
