### ISSUE TITLE
Disable deleting host entries

### ISSUE THREAD

**Issue by Copper-Head** [cogitatio/vagrant-hostsupdater#71]
We just started using your plug-in and we're very thankful for it. I was wondering, however, if there are any plans for adding an option not to undo the changes to the hosts file upon halting the vagrant machine. The nature of our setup doesn't require us to modify that file all too often and the constant prompts for the admin password are a bit annoying. Just to be clear, I have no problem with the prompt itself and understand the need for it, but in our particular case I feel like the rewriting of the hosts file is a bit superfluous.

**Comment by cgsmith** [comment]
@Copper-Head is this only necessary for `vagrant halt` or `vagrant destroy`?

As for the password prompts, that will be addressed in the documentation in an upcoming release.

**Comment by Copper-Head** [comment]
Thanks for getting back and sorry about the delay. I originally saw this as only necessary for `vagrant halt`, since it would be kind of expected to undo this step with `destroy`.

**Comment by cgsmith** [comment]
@Copper-Head I am adding this functionality in 1.0.2

`config.hostsupdater.remove_on_suspend  = false`

You were able to do this in 1.0.1 but it only worked on suspend.  It works on `vagrant suspend` and `vagrant halt` now.  Expect a release soon.
