### ISSUE TITLE
Remove the remaining line feed staying after hosts removal

### ISSUE THREAD

**Issue by e7d** [cogitatio/vagrant-hostsupdater#83]
I've been using this plugin quite intensively recently, and I would address an annoying issue.

In my Vagrantfile, I got 6 aliases referenced on top of the main hostname. As my project is brand new, on the building side, I'm destroying and rebuilding my virtual machines quite often, up to 10 times a day.
I see no problem with the hosts addition, everything comes perfectly. But when it comes to deletion (at vm halt or destroy time), the 7 lines corresponding to my hosts are correctly deleted, but a supplemental line feed remains.
Then each time I rebuild, the hosts are written starting a line lower than the previous time.

That is not a bug as the hosts file remains perfectly functional, but after a bunch of destroy/rebuild or even stop/start cycles, the file becomes really long with a huge useless collection of white line feeds in the middle.

Let me specify I'm using Windows 10, and that i added my user the permissions over the hosts file so i do not need to run vagrant as "Admin".

Addressing this would be great. :)

**Comment by cgsmith** [comment]
This is being addressed with a recent PR. Closing the issue - release of 1.0.2 is coming soon.  Let me know if that addresses this.

**Comment by e7d** [comment]
Yup, perfect ! That does the trick. :)
