### ISSUE TITLE
do not remove hosts entry for already running vm

### ISSUE THREAD

**Issue by hlb-schmidt** [cogitatio/vagrant-hostsupdater#95]
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Removing hosts
==> default: Checking if box 'debian/jessie64' is up to date...
==> default: VirtualBox VM is already running.
```

when doing `vagrant up`, and the machine is already running, vagrant-hostsupdater should not remove the hosts entry.

**Comment by cgsmith** [comment]
@hlb-schmidt this should be fixed.  Try running `vagrant plugin update vagrant-hostsupdater` to update the plugin.

Feel free to reopen if there is still an issue after updating.
