### ISSUE TITLE
Readding host on vagrant up, if the VM is already running

### ISSUE THREAD

**Issue by nepda** [cogitatio/vagrant-hostsupdater#99]
If you run `vagrant up` for a already running VM, the host gets removed, but not re-added:
```
$ vagrant up
Bringing machine 'survivor' up with 'virtualbox' provider...
==> survivor: Removing hosts
[sudo] password for nepda: 
==> survivor: VirtualBox VM is already running.
$
```
It would be nice, if the hostname gets added again after a successful `vagrant up`.

**Comment by cgsmith** [comment]
Please update the plugin by running `vagrant plugin update`
